language: emacs-lisp

# Emacs fails to build using the latest Trusty image on Travis
# See https://github.com/travis-ci/travis-ci/issues/9073
sudo: required
dist: trusty
group: deprecated-2017Q4

addons:
  apt:
    packages:
    - gnutls-bin
      
env:
  - EMACS_TARGET=emacs-24.4
  - EMACS_TARGET=emacs-24.5
  - EMACS_TARGET=emacs-25.1
  - EMACS_TARGET=emacs-25.3
  - EMACS_TARGET=emacs-git

before_install:
  - apt
  - make -f Makefile.travis before_install

install:
  - PATH=~/.cask/bin:$PATH make -f Makefile.travis install

script:
  - emacs --version
  - PATH=~/.cask/bin:$PATH make -f Makefile.travis script

